# -*- coding: utf-8 -*-
"""QR Code Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F91AVF8MNsy5HcUHlXh7cdJSzBtDwSDs
"""

pip install qrcode[pil]

import qrcode

def generate_qr():
    data = input("Enter text or URL to generate QR Code: ")

    qr = qrcode.QRCode(
        version=1,
        box_size=10,
        border=4
    )

    qr.add_data(data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    filename = input("Enter file name (without extension): ")
    img.save(f"{filename}.png")

    print(f"QR Code saved as {filename}.png")

generate_qr()